name: golangci-lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Version 2.5.0 supports Go 1.25 (released Sep 2025)
          version: v2.5

          # Optional: working directory, useful for monorepos
          # working-directory: test

          # Optional: golangci-lint command line arguments.
          # args: --timeout=5m

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
